<a href="https://github.com/xuehangcang/DeepLearning/blob/main/docs/PyTorch/%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/2.张量.ipynb" download=""><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="110" height="20" role="img" aria-label="jupyter: notebook"><title>jupyter: notebook</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="r"><rect width="110" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="49" height="20" fill="#555"/><rect x="49" width="61" height="20" fill="#fe7d37"/><rect width="110" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><text aria-hidden="true" x="255" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="390">jupyter</text><text x="255" y="140" transform="scale(.1)" fill="#fff" textLength="390">jupyter</text><text aria-hidden="true" x="785" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="510">notebook</text><text x="785" y="140" transform="scale(.1)" fill="#fff" textLength="510">notebook</text></g></svg></a>

## 2.1 张量

张量是一种特殊的数据结构，非常类似于数组和矩阵。在 PyTorch 中，我们使用张量来编码模型的输入和输出，以及模型的参数。

张量类似于 `NumPy` 中的 `ndarrays`，但张量可以在 GPU 或其他硬件加速器上运行。实际上，张量和 NumPy 数组通常可以共享相同的底层内存，消除了复制数据的需要。`张量`还针对自动微分进行了优化。`NumPy` 中的 `ndarrays` 熟悉的话，您会对张量 API 感到亲切。如果不熟悉，请跟随我们的步伐！


In [8]:
import torch
import numpy as np

## 2.2 初始化张量

张量可以通过多种方式进行初始化。以下是一些例子：

**从数据中直接创建**

张量可以直接从数据中创建。数据类型会被自动推断。

In [9]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

**从 NumPy 数组创建张量**

张量可以从 NumPy 数组创建。

In [10]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

**来自另一个张量**

新的张量保留了参数张量的属性（形状、数据类型），除非明确覆盖。

In [11]:
x_ones = torch.ones_like(x_data) # 保留了x_data的属性
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # 覆盖了x_data的数据类型
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5579, 0.5803],
        [0.3633, 0.7775]]) 



**随机或常数值：**

`shape` 是张量维度的元组。在下面的函数中，它决定了输出张量的维度。

In [12]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1944, 0.9346, 0.8559],
        [0.7070, 0.1307, 0.4355]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 2.3 张量的属性

张量的属性描述了它们的形状、数据类型和存储设备。


In [13]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 2.4 张量的操作

PyTorch 提供了 100 多种张量操作，包括算术、线性代数、矩阵操作（转置、索引、切片）、采样等等，全部在 `https://pytorch.org/docs/stable/torch.html>` 进行了全面的描述。

每个操作都可以在GPU上运行（通常比在CPU上运行速度更快）。

默认情况下，张量在CPU上创建。我们需要使用 `.to` 方法将张量显式地移动到 GPU 上（在检查GPU可用性之后）。请记住，跨设备复制大型张量可能会花费大量的时间和内存！

如果可用，我们将张量移动到GPU上

In [14]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

尝试使用列表中的一些操作。
如果您熟悉NumPy API，您会发现Tensor API非常易于使用。

 **标准的类似于NumPy的索引和切片操作**

In [15]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**拼接张量**

您可以使用 `torch.cat` 沿着给定维度连接一系列张量。

In [16]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**算术运算**

这将计算两个张量之间的矩阵乘法。y1、y2和y3将具有相同的值。
`tensor.T` 返回张量的转置。

In [17]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

这将计算逐元素乘积。z1、z2、z3 将具有相同的值。

In [18]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

**单元素张量**

如果你有一个只有一个元素的张量，例如将张量中的所有值聚合为一个值，你可以使用 `item()` 将其转换为 `Python` 数值。

In [19]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


**原地操作**

将结果存储到操作数中的操作称为原地操作。它们用 `_` 后缀表示。 虽然就地操作可以节省一些内存，但是在计算导数时可能会出现问题，因为会立即丢失历史记录。因此，我们不建议使用就地操作。

例如：`x.copy_(y)`, `x.t_()` 将会改变 `x`。

In [21]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


## 2.5 使用 NumPy 进行桥接

 CPU 上的张量和 NumPy 数组可以共享它们的底层内存位置，改变其中一个将会改变另一个。

### 2.5.1 将Tensor转换为NumPy数组

In [22]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


张量的变化会反映在 NumPy 数组中。

In [23]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### 2.5.2 将NumPy数组转换为张量

In [25]:
n = np.ones(5)
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

NumPy数组的变化会反映在张量中。

In [26]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
